version: '3'

networks:
  public:
  private:

services:
  
  endpoint:
    image: joshgree/endpoint:${BRANCH:-master}
    ports:
      - $ENDPOINT_LOCAL_PORT:80
    environment: 
      GIN_MODE: release
    networks:
      - public
      - private
  
  requests:
    image: joshgree/requests:${BRANCH:-master}
    networks:
      - public
  
  pg:
    image: joshgree/pg:${BRANCH:-master}
    networks:
      - private

  # zookeeper:
  #   image: scratch

  # broker:
  #   image: scratch

  clustering:
    image: joshgree/clustering:${BRANCH:-master}
    networks:
      - private

  viz:
    image: joshgree/viz:${BRANCH:-master}
    networks:
      - private