version: '3'

services:
  
  endpoint:
    image: joshgree/endpoint:${BRANCH:-master}
    # build: ./endpoint
    ports:
      - $ENDPOINT_LOCAL_PORT:80
    environment: 
      GIN_MODE: release
  
  requests:
    image: joshgree/requests:${BRANCH:-master}
    # build: ./requests
  
  pg:
    image: joshgree/pg:${BRANCH:-master}
    # build: ./pg

  # zookeeper:
  #   image: scratch

  # broker:
  #   image: scratch

  clustering:
    image: joshgree/clustering:${BRANCH:-master}
    # build: ./clustering

  viz:
    image: joshgree/viz:${BRANCH:-master}
    build: ./viz