version: '3'

services:
  
  endpoint:
    image: endpoint:0.1
    build: ./endpoint
  
  requests:
    image: requests:0.1
    build: ./requests
  
  pg:
    image: pg:0.1
    build: ./pg

  # zookeeper:
  #   image: scratch

  # broker:
  #   image: scratch

  clustering:
    image: clustering:0.1
    build: ./clustering

  viz:
    image: viz:0.1
    build: ./viz