version: '3'

networks:
  public:
  private:

services:
  
  endpoint:
    image: joshgree/endpoint:${BRANCH:-master}
    build: ./endpoint
    ports:
      - $ENDPOINT_LOCAL_PORT:80
    environment: 
      GIN_MODE: release
    networks:
      - public
      - private
  
  requests:
    image: joshgree/requests:${BRANCH:-master}
    build: ./requests
    environment: 
      TASK_LIMIT: 1
    networks:
      - public
  
  pg:
    image: joshgree/pg:${BRANCH:-master}
    build: ./pg
    networks:
      - private

  # zookeeper:
  #   image: scratch

  # broker:
  #   image: scratch

  clustering:
    image: joshgree/clustering:${BRANCH:-master}
    build: ./clustering
    networks:
      - private

  viz:
    image: joshgree/viz:${BRANCH:-master}
    build: ./viz
    networks:
      - private