version: '3'

services:
  
  endpoint:
    image: joshgree/endpoint:master
    # build: ./endpoint
  
  requests:
    image: joshgree/requests:master
    # build: ./requests
  
  pg:
    image: joshgree/pg:master
    # build: ./pg

  # zookeeper:
  #   image: scratch

  # broker:
  #   image: scratch

  clustering:
    image: joshgree/clustering:master
    # build: ./clustering

  viz:
    image: joshgree/viz:master
    build: ./viz