version: '3'

networks:
  public:
  private:

services:
  
  endpoint:
    image: joshgree/endpoint:${BRANCH:-master}
    build: ./endpoint
    ports:
      - $ENDPOINT_LOCAL_PORT:80
    environment: 
      GIN_MODE: release
    networks:
      - public
      - private
    depends_on:
      - broker
  
  requests:
    image: joshgree/requests:${BRANCH:-master}
    build: ./requests
    environment: 
      TASK_LIMIT: $TASK_LIMIT
    networks:
      - public
    depends_on:
      - endpoint
  
  pg:
    image: joshgree/pg:${BRANCH:-master}
    build: ./pg
    networks:
      - private
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg
    ports:
      - 5432:5432

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: $ZOOKEEPER_CLIENT_PORT
      ZOOKEEPER_TICK_TIME: 2000
    ports: 
      - $ZOOKEEPER_CLIENT_PORT:$ZOOKEEPER_CLIENT_PORT
    networks:
      - private

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:$ZOOKEEPER_CLIENT_PORT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:$BROKER_ADVERTISED_LISTNER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - private
    ports: 
      - $BROKER_ADVERTISED_LISTNER:$BROKER_ADVERTISED_LISTNER

  clustering:
    image: joshgree/clustering:${BRANCH:-master}
    build: ./clustering
    networks:
      - private

  stream_topic_to_pg:
    image: joshgree/stream_topic_to_pg:${BRANCH:-master}
    build: ./stream_topic_to_pg
    networks:
      - private
    restart: always
    environment:
      KAFKA_BROKER_URL: broker:$BROKER_ADVERTISED_LISTNER
      TRANSACTIONS_TOPIC: response-time-per-route
      PG_URI: postgres://pg:pg@pg:5432/pg
    depends_on:
      - zookeeper
      - broker
      - pg

  stream_topic_to_websocket:
    image: joshgree/stream_topic_to_websocket:${BRANCH:-master}
    build: ./stream_topic_to_websocket
    networks:
      - private
    restart: always
    environment:
      KAFKA_BROKER_URL: broker:$BROKER_ADVERTISED_LISTNER
      TRANSACTIONS_TOPIC: response-time-per-route
    ports:
      - 5678:5678
    depends_on:
      - zookeeper
      - broker

  viz:
    image: joshgree/viz:${BRANCH:-master}
    build: ./viz
    networks:
      - private