version: 2.1

jobs:
  build_and_push_clustering:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/clustering:$CIRCLE_BRANCH clustering
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/clustering:$CIRCLE_BRANCH
  build_and_push_endpoint:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/endpoint:$CIRCLE_BRANCH endpoint
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/endpoint:$CIRCLE_BRANCH
  build_and_push_pg:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/pg:$CIRCLE_BRANCH pg
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/pg:$CIRCLE_BRANCH
  build_and_push_requests:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/requests:$CIRCLE_BRANCH requests
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/requests:$CIRCLE_BRANCH
  build_and_push_viz:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/viz:$CIRCLE_BRANCH viz
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/viz:$CIRCLE_BRANCH
  build_and_push_stream_topic_to_pg:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "build container and tag"
          command: |
            docker build -t joshgree/stream_topic_to_pg:$CIRCLE_BRANCH stream_topic_to_pg
      - run:
          name: Log in to docker cloud
          command: docker login --username $DOCKER_CLOUD_USER --password $DOCKER_CLOUD_PASSWORD
      - run:
          name: Push images to Docker cloud
          command: |
            docker push joshgree/stream_topic_to_pg:$CIRCLE_BRANCH

workflows:
  run_build_pipeline:
    jobs:
      - build_and_push_clustering
      - build_and_push_endpoint
      - build_and_push_pg
      - build_and_push_requests
      - build_and_push_viz